export const INICIAR_SESION = 'INICIAR_SESION';
export const INICIAR_SESION_EXITO = 'INICIAR_SESION_EXITO';
export const INICIAR_SESION_ERROR = 'INICIAR_SESION_ERROR';
export const CARGAR_MENU = 'CARGAR_MENU';
export const CERRAR_SESION = 'CERRAR_SESION';